USE [master]
GO

CREATE DATABASE [BikeStoresUSA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BikeStoresUSA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BikeStoresUSA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BikeStoresUSA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BikeStoresUSA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BikeStoresUSA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BikeStoresUSA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET ARITHABORT OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BikeStoresUSA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BikeStoresUSA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BikeStoresUSA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BikeStoresUSA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET RECOVERY FULL 
GO

ALTER DATABASE [BikeStoresUSA] SET  MULTI_USER 
GO

ALTER DATABASE [BikeStoresUSA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BikeStoresUSA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BikeStoresUSA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BikeStoresUSA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BikeStoresUSA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BikeStoresUSA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BikeStoresUSA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BikeStoresUSA] SET  READ_WRITE 
GO


